"""
Test: Use InsertFamilyTableEdit + DesignTable COM to populate cells.
This is the VBA-equivalent approach for pywin32.
"""
import os, sys, time
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from engine.config import LOCAL_PATHS

MODEL = LOCAL_PATHS["sw_model"]
EXCEL = LOCAL_PATHS["excel"]

import win32com.client, pythoncom, openpyxl
pythoncom.CoInitialize()

# Read Excel data
wb = openpyxl.load_workbook(EXCEL, data_only=True)
ws = wb.active
row1_cells = list(ws.iter_rows(min_row=1, max_row=1))[0]
row1_vals = [c.value for c in row1_cells]
row2_cells = list(ws.iter_rows(min_row=2, max_row=2))[0]
row2_vals = [c.value for c in row2_cells]
excel_params = [str(v) for v in row2_vals[1:] if v is not None]
config_data = {}
for row in ws.iter_rows(min_row=3, values_only=True):
    if row[0] is None: break
    config_data[int(row[0])] = [row[i] for i in range(1, len(excel_params)+1)]
wb.close()
print(f"Params: {excel_params}")
print(f"Configs: {sorted(config_data.keys())}")

try:
    sw = win32com.client.Dispatch("SldWorks.Application")
    sw.Visible = True
    time.sleep(8)

    oe = win32com.client.VARIANT(pythoncom.VT_BYREF | pythoncom.VT_I4, 0)
    ow = win32com.client.VARIANT(pythoncom.VT_BYREF | pythoncom.VT_I4, 0)
    doc = sw.OpenDoc6(MODEL, 1, 1, "", oe, ow)
    print(f"Opened: Errors={oe.value} Warnings={ow.value}")

    # Step 1: Insert empty design table
    print("\n--- Step 1: InsertFamilyTableEdit ---")
    doc.InsertFamilyTableEdit()
    time.sleep(1)
    print("InsertFamilyTableEdit: OK")

    # Step 2: Get DesignTable interface
    print("\n--- Step 2: GetDesignTable ---")
    dt = doc.GetDesignTable
    print(f"DT: {dt}, type={type(dt)}")

    # Step 3: Attach
    print("\n--- Step 3: Attach ---")
    result = dt.Attach
    print(f"Attach: {result}")

    # Step 4: Check dimensions
    print("\n--- Step 4: Table dimensions ---")
    nrows = dt.GetTotalRowCount
    ncols = dt.GetTotalColumnCount
    print(f"Rows: {nrows}, Cols: {ncols}")

    # Step 5: Try to write cells
    # The empty design table has default structure.
    # We need to add our data rows.
    print("\n--- Step 5: Writing design table data ---")

    # Row 1 is auto-generated by SW (header with model name), we keep it
    # Row 2 should have parameter headers — SW may auto-fill some

    # First, let's read what SW generated
    print("Existing content:")
    for r in range(min(5, nrows)):
        row_text = []
        for c in range(min(6, ncols)):
            try:
                cell = dt.GetEntryText(r, c)
                row_text.append(str(cell)[:25] if cell else "(empty)")
            except Exception as e:
                row_text.append(f"ERR:{type(e).__name__}")
        print(f"  Row {r}: {' | '.join(row_text)}")

    # Try to write: we need to figure out the write method
    # Try SetEntryText, SetEntry, put_EntryText, etc.
    write_methods = ["SetEntryText", "SetEntry", "put_EntryText", 
                     "SetText", "put_Text", "SetCellText"]
    for method in write_methods:
        if hasattr(dt, method):
            print(f"Found write method: {method}")
            break
    else:
        print("Searching for write methods...")
        # Try to find any set/put method
        for attr in dir(dt):
            low = attr.lower()
            if ('set' in low or 'put' in low) and ('entry' in low or 'text' in low or 'cell' in low):
                print(f"  Candidate: {attr}")

    # Try writing the Excel data to row 3+
    # The Excel has: row 1=header, row 2=param names (col A empty), row 3+=data
    # The DT has: row 0=header, row 1=param names (col 0=Family?), row 2+=data
    data_start_row = 2  # after header and param row
    try:
        for row_idx, (cfg_name, vals) in enumerate(sorted(config_data.items())):
            r = data_start_row + row_idx
            # Col 0 is config name
            dt.SetEntryText(r, 0, str(cfg_name))
            for col_idx, val in enumerate(vals):
                dt.SetEntryText(r, col_idx + 1, str(val))
            print(f"  Wrote row {r}: config {cfg_name}, values {vals}")
    except AttributeError:
        print("SetEntryText not available. Trying alternative...")
        # In pywin32, methods with parameters might be accessed differently
        # Try: dt._oleobj_.Invoke(dispid, ...)
        try:
            # Dispatch ID for SetEntryText. Need to find it.
            # Alternative: use the Excel application object
            print("  Attempting Excel COM manipulation...")
            
            # The design table opens in Excel. We can get the Excel Application
            # via SW's embedded Excel COM object.
            # swExApp = sw.GetExcelApplication() or similar
            
            # Actually, GetDesignTable returns IDesignTable which might
            # also give us the Excel workbook directly
            try:
                wb_com = dt.GetAttachedExcelWorkbook
                print(f"  Excel workbook: {wb_com}")
            except Exception:
                pass
            try:
                wb_com = dt.GetAttachedExcelWorkbook()
                print(f"  Excel workbook: {wb_com}")
            except Exception:
                pass
        except Exception as e:
            print(f"  All alternatives failed: {type(e).__name__}: {e}")

    # Step 6: Detach and update
    print("\n--- Step 6: Detach and UpdateModel ---")
    dt.Detach
    print("Detach: OK")
    
    # Read back to verify
    dt.Attach
    print("Re-attached, reading back...")
    for r in range(min(15, dt.GetTotalRowCount)):
        row_text = []
        for c in range(min(6, dt.GetTotalColumnCount)):
            try:
                cell = dt.GetEntryText(r, c)
                row_text.append(str(cell)[:20] if cell else "(empty)")
            except Exception:
                row_text.append("ERR")
        print(f"  Row {r}: {' | '.join(row_text)}")
    dt.Detach

    # Try UpdateModel
    try:
        dt.UpdateModel
        print("UpdateModel: OK")
    except Exception as e:
        print(f"UpdateModel: {type(e).__name__}: {e}")

    # Cleanup
    doc.CloseFamilyTable()
    sw.CloseDoc(os.path.basename(MODEL))
    print("\nDone!")
finally:
    pythoncom.CoUninitialize()
